artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion



data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_transformation/
  


data_analysis:
  root_dir: artifacts/data_analysis/
  data_dir: artifacts/data_transformation/


model_trainer:
  root_dir: artifacts/model_trainer/
  data_dir: artifacts/data_analysis/

